meltAssay fix (colData is not added)
microbiome/mia pull request #130
Opened 2021-08-19 14:09 UTC by TuomasBorman

Hi,

I found a bug from `meltAssay`.

**Problem:** 
When `colnames` are in format "1", "2"..., they get prefix "X" when `assay` is melted. E.g., "1" --> "X1". That is because, `data.frame `function checks column names that they are syntactically valid and not duplicated, and "1" is not valid.  

Because prefix is added to non-valid names, `colData` and `melted assay` do not match anymore. --> **`left_join` does not work, and `colData` is not added to `melted data`.** 

Because IDs in format "1" are so common, I think this is a problem.

Example:
```
library(mia)

data("GlobalPatterns")

tse <- GlobalPatterns
tse2 <- tse

# Change the colnames
colnames(tse2) <- seq_along(colnames(tse2))

meltAssay(tse, assay_name = "counts", add_col_data = TRUE)
meltAssay(tse2, assay_name = "counts", add_col_data = TRUE)
```

**Solution:** 
I think that check is not necessary, and it can be disabled. This PR disables it.

-Tuomas

2021-08-19 14:27 UTC, antagomir reviewed
Ok with me but I am wondering if we should give check.names as a function argument that the user can change. It could be FALSE by default.

2021-08-19 15:47 UTC, TuomasBorman commented
>  I am wondering if we should give check.names as a function argument that the user can change

I added that option. When  check_names = TRUE, colData cannot be added, because it would lead just full of NAs, so there is no mean to do that

2021-08-19 15:49 UTC, TuomasBorman commented
> > I am wondering if we should give check.names as a function argument that the user can change
> 
> I added that option. When check_names = TRUE, colData cannot be added, because it would lead just full of NAs, so there is no mean to do that

... that could be the choice of user though, so I can change that

2021-08-19 18:26 UTC, FelixErnst requested changes
Hi Tuoams, 

thanks for the PR.

```r
> meltAssay(tse, abund_values = "counts", add_col_data = TRUE)
# A tibble: 499,616 x 10
   FeatureID SampleID counts X.SampleID Primer  Final_Barcode Barcode_truncated_plus_T Barcode_full_length SampleType Description       
   <fct>     <fct>     <dbl> <fct>      <fct>   <fct>         <fct>                    <fct>               <fct>      <fct>             
 1 549322    CL3           0 CL3        ILBC_01 AACGCA        TGCGTT                   CTAGCGTGCGT         Soil       "Calhoun South Ca~
 2 549322    CC1           0 CC1        ILBC_02 AACTCG        CGAGTT                   CATCGACGAGT         Soil       "Cedar Creek Minn~
 3 549322    SV1           0 SV1        ILBC_03 AACTGT        ACAGTT                   GTACGCACAGT         Soil       "Sevilleta new Me~
 4 549322    M31Fcsw       0 M31Fcsw    ILBC_04 AAGAGA        TCTCTT                   TCGACATCTCT         Feces      "M3, Day 1, fecal~
 5 549322    M11Fcsw       0 M11Fcsw    ILBC_05 AAGCTG        CAGCTT                   CGACTGCAGCT         Feces      "M1, Day 1, fecal~
 6 549322    M31Plmr       0 M31Plmr    ILBC_07 AATCGT        ACGATT                   CGAGTCACGAT         Skin       "M3, Day 1, right~
 7 549322    M11Plmr       0 M11Plmr    ILBC_08 ACACAC        GTGTGT                   GCCATAGTGTG         Skin       "M1, Day 1, right~
 8 549322    F21Plmr       0 F21Plmr    ILBC_09 ACACAT        ATGTGT                   GTAGACATGTG         Skin       "F1, Day 1,  righ~
 9 549322    M31Tong       0 M31Tong    ILBC_10 ACACGA        TCGTGT                   TGTGGCTCGTG         Tongue     "M3, Day 1, tongu~
10 549322    M11Tong       0 M11Tong    ILBC_11 ACACGG        CCGTGT                   TAGACACCGTG         Tongue     "M1, Day 1, tongu~
# ... with 499,606 more rows
> meltAssay(tse, abund_values = "counts", add_col_data = TRUE, check_names = TRUE)
# A tibble: 499,616 x 3
   FeatureID SampleID counts
   <fct>     <fct>     <dbl>
 1 549322    CL3           0
 2 549322    CC1           0
 3 549322    SV1           0
 4 549322    M31Fcsw       0
 5 549322    M11Fcsw       0
 6 549322    M31Plmr       0
 7 549322    M11Plmr       0
 8 549322    F21Plmr       0
 9 549322    M31Tong       0
10 549322    M11Tong       0
# ... with 499,606 more rows
```

This cannot be right. `check_names` overwrites `add_col_data`...

I think, you forgot to pass the setting along with `.add_col_data_to_molten_assay`.

2021-08-19 19:00 UTC, TuomasBorman commented
That was actually intentional. I wanted to overwrite `add_col_data`,  because I was only thinking about the case when samples have names in "1" format. Then `colData` would be full of NAs in melted data.  So it was my mistake

Currently:
```
> meltAssay(tse, abund_values = "counts", add_col_data = TRUE)
# A tibble: 499,616 × 10
   FeatureID SampleID counts X.SampleID Primer  Final_Barcode Barcode_truncated_plus_T Barcode_full_length SampleType Description           
   <fct>     <fct>     <dbl> <fct>      <fct>   <fct>         <fct>                    <fct>               <fct>      <fct>                 
 1 549322    CL3           0 CL3        ILBC_01 AACGCA        TGCGTT                   CTAGCGTGCGT         Soil       "Calhoun South Caroli…
 2 549322    CC1           0 CC1        ILBC_02 AACTCG        CGAGTT                   CATCGACGAGT         Soil       "Cedar Creek Minnesot…
 3 549322    SV1           0 SV1        ILBC_03 AACTGT        ACAGTT                   GTACGCACAGT         Soil       "Sevilleta new Mexico…
 4 549322    M31Fcsw       0 M31Fcsw    ILBC_04 AAGAGA        TCTCTT                   TCGACATCTCT         Feces      "M3, Day 1, fecal swa…
 5 549322    M11Fcsw       0 M11Fcsw    ILBC_05 AAGCTG        CAGCTT                   CGACTGCAGCT         Feces      "M1, Day 1, fecal swa…
 6 549322    M31Plmr       0 M31Plmr    ILBC_07 AATCGT        ACGATT                   CGAGTCACGAT         Skin       "M3, Day 1, right pal…
 7 549322    M11Plmr       0 M11Plmr    ILBC_08 ACACAC        GTGTGT                   GCCATAGTGTG         Skin       "M1, Day 1, right pal…
 8 549322    F21Plmr       0 F21Plmr    ILBC_09 ACACAT        ATGTGT                   GTAGACATGTG         Skin       "F1, Day 1,  right pa…
 9 549322    M31Tong       0 M31Tong    ILBC_10 ACACGA        TCGTGT                   TGTGGCTCGTG         Tongue     "M3, Day 1, tongue, w…
10 549322    M11Tong       0 M11Tong    ILBC_11 ACACGG        CCGTGT                   TAGACACCGTG         Tongue     "M1, Day 1, tongue, w…
# … with 499,606 more rows
> meltAssay(tse, abund_values = "counts", add_col_data = TRUE, check_names = TRUE)
# A tibble: 499,616 × 10
   FeatureID SampleID counts X.SampleID Primer  Final_Barcode Barcode_truncated_plus_T Barcode_full_length SampleType Description           
   <fct>     <fct>     <dbl> <fct>      <fct>   <fct>         <fct>                    <fct>               <fct>      <fct>                 
 1 549322    CL3           0 CL3        ILBC_01 AACGCA        TGCGTT                   CTAGCGTGCGT         Soil       "Calhoun South Caroli…
 2 549322    CC1           0 CC1        ILBC_02 AACTCG        CGAGTT                   CATCGACGAGT         Soil       "Cedar Creek Minnesot…
 3 549322    SV1           0 SV1        ILBC_03 AACTGT        ACAGTT                   GTACGCACAGT         Soil       "Sevilleta new Mexico…
 4 549322    M31Fcsw       0 M31Fcsw    ILBC_04 AAGAGA        TCTCTT                   TCGACATCTCT         Feces      "M3, Day 1, fecal swa…
 5 549322    M11Fcsw       0 M11Fcsw    ILBC_05 AAGCTG        CAGCTT                   CGACTGCAGCT         Feces      "M1, Day 1, fecal swa…
 6 549322    M31Plmr       0 M31Plmr    ILBC_07 AATCGT        ACGATT                   CGAGTCACGAT         Skin       "M3, Day 1, right pal…
 7 549322    M11Plmr       0 M11Plmr    ILBC_08 ACACAC        GTGTGT                   GCCATAGTGTG         Skin       "M1, Day 1, right pal…
 8 549322    F21Plmr       0 F21Plmr    ILBC_09 ACACAT        ATGTGT                   GTAGACATGTG         Skin       "F1, Day 1,  right pa…
 9 549322    M31Tong       0 M31Tong    ILBC_10 ACACGA        TCGTGT                   TGTGGCTCGTG         Tongue     "M3, Day 1, tongue, w…
10 549322    M11Tong       0 M11Tong    ILBC_11 ACACGG        CCGTGT                   TAGACACCGTG         Tongue     "M1, Day 1, tongue, w…
# … with 499,606 more rows
```

2021-08-19 19:13 UTC, FelixErnst commented
How about

```r
meltAssay(tse, abund_values = "counts", add_col_data = TRUE)
meltAssay(tse, abund_values = "counts", add_col_data = TRUE, check_names = TRUE)
```

?

2021-08-19 19:16 UTC, TuomasBorman commented
```
> tse <- GlobalPatterns
> tse2 <- tse
> # Change the colnames
> colnames(tse2) <- seq_along(colnames(tse2))
> meltAssay(tse2, abund_values = "counts", add_col_data = TRUE)
# A tibble: 499,616 × 10
   FeatureID SampleID counts X.SampleID Primer  Final_Barcode Barcode_truncated_plus_T Barcode_full_length SampleType Description           
   <fct>     <fct>     <dbl> <fct>      <fct>   <fct>         <fct>                    <fct>               <fct>      <fct>                 
 1 549322    1             0 CL3        ILBC_01 AACGCA        TGCGTT                   CTAGCGTGCGT         Soil       "Calhoun South Caroli…
 2 549322    2             0 CC1        ILBC_02 AACTCG        CGAGTT                   CATCGACGAGT         Soil       "Cedar Creek Minnesot…
 3 549322    3             0 SV1        ILBC_03 AACTGT        ACAGTT                   GTACGCACAGT         Soil       "Sevilleta new Mexico…
 4 549322    4             0 M31Fcsw    ILBC_04 AAGAGA        TCTCTT                   TCGACATCTCT         Feces      "M3, Day 1, fecal swa…
 5 549322    5             0 M11Fcsw    ILBC_05 AAGCTG        CAGCTT                   CGACTGCAGCT         Feces      "M1, Day 1, fecal swa…
 6 549322    6             0 M31Plmr    ILBC_07 AATCGT        ACGATT                   CGAGTCACGAT         Skin       "M3, Day 1, right pal…
 7 549322    7             0 M11Plmr    ILBC_08 ACACAC        GTGTGT                   GCCATAGTGTG         Skin       "M1, Day 1, right pal…
 8 549322    8             0 F21Plmr    ILBC_09 ACACAT        ATGTGT                   GTAGACATGTG         Skin       "F1, Day 1,  right pa…
 9 549322    9             0 M31Tong    ILBC_10 ACACGA        TCGTGT                   TGTGGCTCGTG         Tongue     "M3, Day 1, tongue, w…
10 549322    10            0 M11Tong    ILBC_11 ACACGG        CCGTGT                   TAGACACCGTG         Tongue     "M1, Day 1, tongue, w…
# … with 499,606 more rows
> meltAssay(tse2, abund_values = "counts", add_col_data = TRUE, check_names = TRUE)
# A tibble: 499,616 × 10
   FeatureID SampleID counts X.SampleID Primer Final_Barcode Barcode_truncated_plus_T Barcode_full_length SampleType Description
   <fct>     <fct>     <dbl> <fct>      <fct>  <fct>         <fct>                    <fct>               <fct>      <fct>      
 1 549322    X1            0 NA         NA     NA            NA                       NA                  NA         NA         
 2 549322    X2            0 NA         NA     NA            NA                       NA                  NA         NA         
 3 549322    X3            0 NA         NA     NA            NA                       NA                  NA         NA         
 4 549322    X4            0 NA         NA     NA            NA                       NA                  NA         NA         
 5 549322    X5            0 NA         NA     NA            NA                       NA                  NA         NA         
 6 549322    X6            0 NA         NA     NA            NA                       NA                  NA         NA         
 7 549322    X7            0 NA         NA     NA            NA                       NA                  NA         NA         
 8 549322    X8            0 NA         NA     NA            NA                       NA                  NA         NA         
 9 549322    X9            0 NA         NA     NA            NA                       NA                  NA         NA         
10 549322    X10           0 NA         NA     NA            NA                       NA                  NA         NA         
# … with 499,606 more rows
```

2021-08-20 09:55 UTC, TuomasBorman commented
This was easily fixable when I though this again

```
> tse <- GlobalPatterns
> tse2 <- tse
> meltAssay(tse2, abund_values = "counts", add_col_data = TRUE)
# A tibble: 499,616 × 10
   FeatureID SampleID counts X.SampleID Primer  Final_Barcode Barcode_truncated_plus_T Barcode_full_length SampleType Description           
   <fct>     <fct>     <dbl> <fct>      <fct>   <fct>         <fct>                    <fct>               <fct>      <fct>                 
 1 549322    CL3           0 CL3        ILBC_01 AACGCA        TGCGTT                   CTAGCGTGCGT         Soil       "Calhoun South Caroli…
 2 549322    CC1           0 CC1        ILBC_02 AACTCG        CGAGTT                   CATCGACGAGT         Soil       "Cedar Creek Minnesot…
 3 549322    SV1           0 SV1        ILBC_03 AACTGT        ACAGTT                   GTACGCACAGT         Soil       "Sevilleta new Mexico…
 4 549322    M31Fcsw       0 M31Fcsw    ILBC_04 AAGAGA        TCTCTT                   TCGACATCTCT         Feces      "M3, Day 1, fecal swa…
 5 549322    M11Fcsw       0 M11Fcsw    ILBC_05 AAGCTG        CAGCTT                   CGACTGCAGCT         Feces      "M1, Day 1, fecal swa…
 6 549322    M31Plmr       0 M31Plmr    ILBC_07 AATCGT        ACGATT                   CGAGTCACGAT         Skin       "M3, Day 1, right pal…
 7 549322    M11Plmr       0 M11Plmr    ILBC_08 ACACAC        GTGTGT                   GCCATAGTGTG         Skin       "M1, Day 1, right pal…
 8 549322    F21Plmr       0 F21Plmr    ILBC_09 ACACAT        ATGTGT                   GTAGACATGTG         Skin       "F1, Day 1,  right pa…
 9 549322    M31Tong       0 M31Tong    ILBC_10 ACACGA        TCGTGT                   TGTGGCTCGTG         Tongue     "M3, Day 1, tongue, w…
10 549322    M11Tong       0 M11Tong    ILBC_11 ACACGG        CCGTGT                   TAGACACCGTG         Tongue     "M1, Day 1, tongue, w…
# … with 499,606 more rows
> meltAssay(tse2, abund_values = "counts", add_col_data = TRUE, check_names = TRUE)
# A tibble: 499,616 × 10
   FeatureID SampleID counts X.SampleID Primer  Final_Barcode Barcode_truncated_plus_T Barcode_full_length SampleType Description           
   <fct>     <fct>     <dbl> <fct>      <fct>   <fct>         <fct>                    <fct>               <fct>      <fct>                 
 1 549322    CL3           0 CL3        ILBC_01 AACGCA        TGCGTT                   CTAGCGTGCGT         Soil       "Calhoun South Caroli…
 2 549322    CC1           0 CC1        ILBC_02 AACTCG        CGAGTT                   CATCGACGAGT         Soil       "Cedar Creek Minnesot…
 3 549322    SV1           0 SV1        ILBC_03 AACTGT        ACAGTT                   GTACGCACAGT         Soil       "Sevilleta new Mexico…
 4 549322    M31Fcsw       0 M31Fcsw    ILBC_04 AAGAGA        TCTCTT                   TCGACATCTCT         Feces      "M3, Day 1, fecal swa…
 5 549322    M11Fcsw       0 M11Fcsw    ILBC_05 AAGCTG        CAGCTT                   CGACTGCAGCT         Feces      "M1, Day 1, fecal swa…
 6 549322    M31Plmr       0 M31Plmr    ILBC_07 AATCGT        ACGATT                   CGAGTCACGAT         Skin       "M3, Day 1, right pal…
 7 549322    M11Plmr       0 M11Plmr    ILBC_08 ACACAC        GTGTGT                   GCCATAGTGTG         Skin       "M1, Day 1, right pal…
 8 549322    F21Plmr       0 F21Plmr    ILBC_09 ACACAT        ATGTGT                   GTAGACATGTG         Skin       "F1, Day 1,  right pa…
 9 549322    M31Tong       0 M31Tong    ILBC_10 ACACGA        TCGTGT                   TGTGGCTCGTG         Tongue     "M3, Day 1, tongue, w…
10 549322    M11Tong       0 M11Tong    ILBC_11 ACACGG        CCGTGT                   TAGACACCGTG         Tongue     "M1, Day 1, tongue, w…
# … with 499,606 more rows
```

2021-08-20 18:53 UTC, FelixErnst approved these changes
Please bump the version, write a test or two and merge. Thanks

2021-08-20 19:45 UTC, merged