Added estimateOverlap
microbiome/mia pull request #150
Opened 2021-10-07 06:42 UTC by TuomasBorman

Hi,

here is the implementation of [`microbiome::overlap`](https://github.com/microbiome/microbiome/blob/master/R/overlap.R). 

**I compared `microbiome::overlap` with [`Gao's overlap`](https://github.com/Russel88/DOC)**

- 	Gao returns a list of overlap and **rJSD (root Jensen-Shannon divergence)** (and a dataframe with Overlap and rJSD as vectors) / microbiome only overlap
- 	**Overlap is similar**, microbiome has only option for relabundance, Gao does not restrict this
- 	Gao does not have detection threshold

**Jensen-Shannon divergence**

- 	We have this already implemented --> `calculateJSD`
- 	rJSD in matrix format `sqrt(as.matrix(calculateJSD(tse)))`
- 	However, this method does not have detection threshold, should there be one?
- 	(Man page does not have a formula, I can add)
- 	**Is this commonly used as an overlap estimate? If so, should estimateOverlap have new parameter `index`(?) that have options overlap, JSD, and rJSD? `estimateOverlap(x, index = c("overlap", "JSD", rJSD"), detection = 0)`**

Issue: https://github.com/microbiome/mia/issues/60

-Tuomas

2021-10-10 09:08 UTC, antagomir commented
Can we view "overlap" as one type of dissimilarity matrix? If there are no relevant differences, we could implement this in the same way than `calculateJSD`, `calculateUnifrac`..  in that case the name could also be `calculateOverlap`.. ?

2021-10-15 15:39 UTC, FelixErnst requested changes
Hi Tuomas,

thanks for the PR.

Can you seperate the renaming things from the implementation. I don't think there is a link between the two things, is there?

Also remember, that you have to support legacy code now. This renaming could potentially break someones code. Just add an `abund_values = exprs_values` as an argument and use the abund_values argument internally. Modify the man pages accordingly.

Best
Felix

2021-10-16 16:32 UTC, FelixErnst approved these changes

2021-10-16 16:32 UTC, FelixErnst commented on R/calculateOverlap.R
> +}
Can you fix the indentation, bump the version, amend the NEWS and merge?

2021-10-16 17:10 UTC, FelixErnst requested changes
Another thing: Shouldn't the function be called `estimateOverlap` as the PR title suggests?

@antagomir

2021-10-23 20:28 UTC, FelixErnst commented
Any news on this regarding the function name?

2021-10-24 07:34 UTC, antagomir commented
> Another thing: Shouldn't the function be called `estimateOverlap` as the PR title suggests?

My earlier comment: "Can we view "overlap" as one type of dissimilarity matrix? If there are no relevant differences, we could implement this in the same way than `calculateJSD`, `calculateUnifrac`.. in that case the name could also be `calculateOverlap`.. ?" -> the title suggested `estimateOverlap` but perhaps we can change this now to make it consistent with the other dissimilarity measures?

2021-10-27 17:41 UTC, FelixErnst commented
test it, bump it, NEWS add it (Think about that one Daft Punk song, when reading)

2021-10-27 18:13 UTC, TuomasBorman commented
Lol, I had to play it

2021-10-29 07:34 UTC, TuomasBorman commented
I added `runOverlap`. It stores result to `reducedDim`.

2021-11-05 12:41 UTC, merged