Issue127
microbiome/mia pull request #160
Opened 2021-11-01 13:33 UTC by shigdel

renamed and changed the content   CalculatedUnifrac to CalculatedUnifrac

2021-11-01 13:36 UTC, ChouaibB requested changes
File should be renamed as "calculateUnifrac"

2021-11-01 13:48 UTC, ChouaibB approved these changes

2021-11-02 07:53 UTC, TuomasBorman requested changes
Hi, thanks for the PR!

Now you have two pull requests open for this same thing. In addition to this, you have opened PRs https://github.com/microbiome/mia/pull/153 and https://github.com/microbiome/mia/pull/129 (already closed) which are related to the issue https://github.com/microbiome/mia/issues/127

It is better to have one PR for one thing to simplify things. Because now some discussions are in  another PR, and this is some kind of documentation about what we have done and why we haven't done some things. 

If you want to revert / undo things that you have made to your branch, that is always possible

**So, for the future PRs: one issue = one PR is better**

Also, you are merging this to `microbiome:issue127` branch and not to `master`. Is there any reason for that? **I think you should merge this directly into the master.** 

That can be easily changed: 

1. press edit (next to the PR title)
2. change base: issue127 to master

Otherwise looks good

2021-11-02 10:21 UTC, antagomir commented
I would support that only specific core maintainers will merge PRs to master.

2021-11-02 10:37 UTC, TuomasBorman commented
> I would support that only specific core maintainers will merge PRs to master.

Well that might be actually better for example because of the limitations of testing when project is forked

2021-11-02 12:46 UTC, TuomasBorman approved these changes

2021-11-03 11:37 UTC, FelixErnst commented
Please add a new generic for the old name, add a deprected note, specifically explaining the tiny renaming part. Thanks

2021-11-06 16:04 UTC, antagomir commented
@shigdel let us know if there are any problems with implementing the proposed changes -

2021-11-08 17:02 UTC, FelixErnst commented
This PR is not aimed at the master branch. Are you aware of that?

2021-11-08 17:08 UTC, TuomasBorman commented
> This PR is not aimed at the master branch. Are you aware of that?

Yes, that is intentional. This allows, e.g., us to test it before merging into master

2021-11-08 17:21 UTC, TuomasBorman commented
Maybe best to revert that sync, because this is quite a mess

2021-11-08 17:49 UTC, TuomasBorman commented on R/calculateUnifrac.R
>  )
message

2021-11-08 18:07 UTC, TuomasBorman commented
Branch `issue127_new` includes these changes without conflicts. I'm not sure what would have been the best practice in this case, because now it shows only myself as a contributor

2021-11-14 10:16 UTC, FelixErnst commented
Can you update from master, to get a current idea of the changes? Thanks

2021-11-14 17:06 UTC, TuomasBorman commented
How this should be done correctly? 

If I update `shigdel/issue127` from `microbiome/master` over 50 commits appears, because it is not synced. At least last time it showed that all those all 50 commits were new modifications. 

Or should we continue with `issue127_new` branch? This kind of git problems are not too familiar to me

2021-11-14 17:44 UTC, antagomir commented
If this is just about renaming UniFrac -> Unifrac, perhaps easier to redo all with a clean branch?

2021-11-15 06:48 UTC, closed without merging