Get top taxa rank option
microbiome/mia pull request #213
Opened 2022-01-24 08:54 UTC by TuomasBorman

Hi,

I added rank option to `getTopTaxa`. 

We use `na.rm` in two places. 

1. To remove NAs when calculating, e.g., rowsums
2. To remove NAs while agglomerating

In other summary functions, na.rm is used as a hidden (`...`) argument for `agglomerateByRank` (option 2), so I changed na.rm (option 1) to `remove_na`. 

Issue: https://github.com/microbiome/mia/issues/212

-Tuomas

2022-01-24 16:03 UTC, antagomir commented on R/summaries.R
>  #'              specified to argument \code{method}. Default is TRUE.
Hmm now I am puzzled which way this should be. In a vaaast number of R functions, they use `na.rm`. I would stick to that just for compatibility reasons.

2022-01-25 11:24 UTC, microsud commented on R/summaries.R
>  #'              specified to argument \code{method}. Default is TRUE.
I prefer `getTopTaxa` as it is now because this is very simple for users to do and avoids a lot of code for us to maintain `getTopTaxa` depending on `agglomerateByRank` and so on. 
```
top_families <- agglomerateByRank(tse, rank="Family", na.rm = TRUE) %>% getTopTaxa(...)
```

2022-02-06 10:55 UTC, FelixErnst requested changes
I am not sure about his, because I don't see the point.

This works doesn't it?

```r
getTopTaxa(agglomerateByRank(x, rank = "Genus", na.rm=TRUE))
```

2022-02-06 11:56 UTC, antagomir commented
Yep, perhaps that would be sufficient. It could be added as an example in `getTopTaxa` manpage so that less educated users can get in speed more rapidly.

2022-02-06 12:00 UTC, antagomir commented
I would keep this open until the example has been added. Otherwise we will forget.

2022-02-06 12:01 UTC, closed without merging

2022-02-06 12:01 UTC, FelixErnst commented
Guess what I did... 😄