Deprecate taxonomyTree and addTaxonomyTree
microbiome/mia pull request #496
Opened 2024-02-27 11:34 UTC by thpralas

Replace `taxonomyTree` with `getHierarchyTree` and `addTaxonomyTree` with `addTree`. 

Create new `deprecate` R script and manual page.

Create new `get-values` manual page.

2024-02-27 12:50 UTC, TuomasBorman requested changes
Remember to run BiocCheck

2024-02-27 12:50 UTC, TuomasBorman commented on R/taxonomy.R
> +#' @name get-values
The name should be getHiearchyTree

2024-02-27 12:50 UTC, TuomasBorman commented on R/taxonomy.R
> +setGeneric("addTree",
This name should be addHierarchyTree

2024-02-27 12:50 UTC, TuomasBorman commented on NEWS
> ++ Deprecate taxonomyTree, addTaxonomyTree
Say what are the new names --> maybe that replaced functions x and y with y and z

2024-02-29 15:48 UTC, TuomasBorman requested changes
Almost there

2024-02-29 15:48 UTC, TuomasBorman commented on R/taxonomy.R
> -                                      to_drop,
Add ape::drop.tip with importFrom tag (check other functions)

2024-02-29 15:48 UTC, TuomasBorman commented on R/deprecate.R
> +                                        "Use 'addHierarchyTree' instead."))
Do not add new line ("\n"). It is tidier without (because there might be multiple warnings

2024-02-29 15:48 UTC, TuomasBorman commented on R/taxonomy.R
> +#' @rdname get-values
This name should be hierarchy-tree. Also add the same name above addHierarchyTree -->

1. There should not be get-values page.
2. There should be hiearachy-tree page
3. The title of hiarchy-tree page should be something like ("calculate hireachy tree)
4. *HiearchyTree functions should be removed from taxonomy-methods page.


See man directory. There is manual pages. Check the corresponding pages that they are correct. (In RStudio, you can click the file and then preview.)

2024-03-01 16:01 UTC, TuomasBorman approved these changes
I think this is good to go.

@antagomir

2024-03-01 16:45 UTC, antagomir commented
Some final things, sorry...

Is there a risk that `addTree()` gets mixed with other types of trees? Should it be `addHierarchyTree()`, or is it more generic so that you can use addTree for different things?

It is essential to update the OMA as well, or at least have a clear scheduled plan how that is done.

2024-03-01 17:03 UTC, TuomasBorman commented
Actually it is now `addHiearchyTree`. It is just for adding calculated tree (not generic function for adding any kind of trees)

Updating OMA and other packages is taken into account. We have planned with @thpralas that names are changed everywhere immediately when PR in mia is merged

2024-03-02 10:47 UTC, antagomir commented
Ah great!

2024-03-04 13:51 UTC, merged