changed diversity input check
microbiome/mia pull request #520
Opened 2024-04-18 08:17 UTC by Insaynoah

I changed around the input check for the index as suggested in #519 . Sorry for the headache caused by #514.

2024-04-18 14:52 UTC, TuomasBorman commented
No problem at all, it is maintainers job to evaluate the code, and I don't assume that you know yet all the things in mia. The main goal is to develop good things with the best possible quality.

1. Can you modify also TreeSE method (same thing there, but now with additional faith index)
2. Run BiocCheck::BiocCheck() (Check that the code added by you passes Bioconductor recommendations. There are warnings related to other lines, skip those.)
3. Run manual tests that the code does what it should do. (Can you run the code from the issue? Can you print the code and output here?)

2024-04-18 14:56 UTC, TuomasBorman requested changes

2024-04-18 14:56 UTC, TuomasBorman commented on R/estimateDiversity.R
> +        }
Looks good! Also check that the length of index is over 0 (it is not checked currently. NULL might cause problems --> test `index = NULL`

2024-04-19 07:07 UTC, ndegunst commented
Thanks for the tips !

I ran the BiocCheck with no warnings for the lines I modified and I ran some manual tests on top of the already existing tests, here are the results :

```R

tse <- estimateDiversity(tse, 
                              assay.type = "counts",
                              index = "test", 
                              name = "shannon")

```

Output : 
```
Error: 'index' contains unsupported indices.

```

```R
tse <- estimateDiversity(tse, 
                         assay.type = "counts",
                         name = "shannon")
```

Output : 
```
Error: 'name' must be a non-empty character value and have the same length as 'index'.

```

```R

tse <- estimateDiversity(tse, assay.type = "counts"
                         , index = NULL,
                         name = "test")

```

Output : 
```
Error in .local(x, assay.type, assay_name, index, name, ...) : 
  No 'index' specified.

```

Would you rather have it so that it throws an index error or a name error ?

2024-04-19 13:23 UTC, TuomasBorman commented on R/estimateDiversity.R
> +            stop("No 'index' specified.")
Remember to add call. = FALSE (test what it does)

2024-04-19 13:25 UTC, TuomasBorman commented on R/estimateDiversity.R
> +        }
Also you could remove this check and modify the test below

2024-04-19 13:30 UTC, TuomasBorman commented on R/estimateDiversity.R
> +        if( !all( index %in% supported_index ) ){
This check could test

1. length > 0
2. All values are supported

The error message could be:

"'index' must be a character value specifying alpha diversity index to be calculated. Choose from the following options: ..."

In ... you could print supported types. Something like thia

`stop("'", paste0(supported_types, collapse = "', '"), "'", call. = FALSE)`

2024-04-29 06:21 UTC, TuomasBorman commented
Looks good! Run `BiocCheck::BiocCheck()` and fix everything related to these added lines. (There are some other things related to other lines, but let's keep them unchanged at this point)

2024-04-29 08:08 UTC, Insaynoah commented
That should do it, we shouldn't use collapse within a paste call and if we do past it shouldn't be within a stop call. Therefore, I assembled the string before using it in the stop function.

2024-05-02 07:46 UTC, Insaynoah commented
It should be good now, bioconductor doesn't allow a paste statement within a stop so i created a new variable that pastes the allowed indices before passing it to the stop function.

2024-05-02 13:29 UTC, TuomasBorman commented on R/estimateDiversity.R
> +            stop(paste("Unsupported index:", index_string), call. = FALSE)
The error message could still be more informative.

"'index' must be from the following options:"

2024-05-02 13:30 UTC, TuomasBorman commented on R/estimateDiversity.R
> +
Remove extra line (one is enough)

With these, good to go

2024-05-05 16:45 UTC, TuomasBorman approved these changes

2024-05-05 16:45 UTC, merged