Issue 445 map taxonomy
microbiome/mia pull request #533
Opened 2024-04-25 08:18 UTC by Insaynoah

I optimized the mapTaxonomy function as indicated in #445 by mapping over unique taxa and then mapping back to the original data. Even though the time difference by optimizing doesn't seem staggering, it still improved a little bit.

2024-05-05 07:00 UTC, TuomasBorman approved these changes
Seems working.

Couple of notes:

1. Have you run BiocChec::BiocCheck() to check that these additions follow the guidelines of Bioconductor? --> You could state that you have done that

2.

There are lots of additional lines. This same could be done with only one additional line `taxa <- unique(taxa)`. You could state in PR why you have modified all these lines. Probably there is good reason but reviewing is easier if we know why something has been done. (Correcting the code based on BiocCheck is good reason).

Also, important thing to note is that people are using these methods. We should not modify them without good justification; rather we should avoid making changes. If user checks the code, it seems that everything has changed, and that does not give good impression. (of course we should continuously improve the code)

2024-05-05 07:00 UTC, TuomasBorman commented on R/taxonomy.R
> +              unique_taxa <- unique(taxa)
Is this variable used?

2024-05-05 07:00 UTC, TuomasBorman commented on R/taxonomy.R
> +              unique_taxa <- unique(taxa)
--> yes in line 623

However, it would be more simple to use it also in line 615 and 618 instead of calculating unique values again

2024-05-05 07:00 UTC, TuomasBorman commented on R/taxonomy.R
> +              names(r_fs) <- unique_taxa
These lines do the same thing?

2024-05-05 07:00 UTC, TuomasBorman commented on R/taxonomy.R
> +              ans
use return(ans)

2024-05-05 07:03 UTC, TuomasBorman commented on R/taxonomy.R
> +              unique_taxa <- unique(taxa)
Or maybe the best solution would be to modify line to `taxa <- unique(taxa)`. By doing that, only one line needs to be changed

2024-05-05 07:17 UTC, TuomasBorman requested changes
Also was this the intention of the issue @antagomir 

It seems that this fixes the problem described in the issue, but the speed improvement seems to be very limited. Since I don't know the use case. With `taxa`, user can specify pattern that is fetched from the `rowData`. This modification would improve the performance when

`mapTaxonomy(tse, taxa = c("Escherichia", "Escherichia")) `

--> only one output is returned

2024-05-06 06:50 UTC, Insaynoah commented
I implemented the requested changes and ran the biocCheck which didn't seem to have any issue with the new lines. The taxa have to be mapped back to the originial data. Hence the reason it didn't considerably decrease the computation time.

2024-05-06 06:51 UTC, Insaynoah commented
However, I noticed that the issue was closed just after I made the PR. Was this already fixed ?

2024-05-06 07:48 UTC, antagomir commented
Perhaps my mistake - I reopened it.

2024-05-06 08:32 UTC, TuomasBorman commented
> I implemented the requested changes and ran the biocCheck which didn't seem to have any issue with the new lines. The taxa have to be mapped back to the originial data. Hence the reason it didn't considerably decrease the computation time.

OK, cool! Hmmm, I ran the BiocCheck and it seems that these new lines are incorrectly indented (should be multiplication of 4 spaces). The indentation in old lines were correct, so I think you should revert the changes related to lines that are not really fixing the problem mentioned in the issue. Sorry about extra work

https://contributions.bioconductor.org/r-code.html?q=indentation#indentation

2024-06-04 14:06 UTC, TuomasBorman commented
The indentation is still off. If there is juts couple lines that you are planning to change, you can create new PR and link this with that

2024-06-26 12:05 UTC, antagomir commented
@Insaynoah what's the status of this PR? Can we get it fixed.

2024-07-10 07:00 UTC, TuomasBorman commented
Closing. The following PR will fix the issue https://github.com/microbiome/mia/pull/600

2024-07-10 07:00 UTC, closed without merging