fix addDominant test
microbiome/mia pull request #567
Opened 2024-06-05 10:43 UTC by thpralas

This PR aims to fix the following failing test:
```
── Failure ('test-5dominantTaxa.R:44:9'): getDominant ──────────────────────────
colData(addDominant(tse, rank = "Genus", na.rm = FALSE, name = "dominant"))$dominant[1:15] not equal to `exp.vals.two`.
8/15 mismatches
x[1]: "Class:Thermoprotei"
y[1]: "Genus:CandidatusSolibacter"

x[2]: "Class:Thermoprotei"
y[2]: "Genus:MC18"

x[3]: "Class:Thermoprotei"
y[3]: "Class:Chloracidobacteria"

x[7]: "Class:Thermoprotei"
y[7]: "Family:Moraxellaceae"

x[12]: "Class:Thermoprotei"
y[12]: "Family:ACK-M1"
```
The issue was that the default value of `onRankOnly` in `agglomerateByRank` is `TRUE` so `addDominant` needed to be explicitly called with `onRankOnly = FALSE` as it was done for `getDominant`.

2024-06-06 10:15 UTC, TuomasBorman commented
Alright, thanks for checking this. So this PR https://github.com/microbiome/mia/pull/556/files should already fix the problem. Let's wait until the PR is merged and check.

2024-06-06 10:15 UTC, TuomasBorman requested changes
Wait until the https://github.com/microbiome/mia/pull/556/files is merged

2024-06-11 13:27 UTC, TuomasBorman commented
Can you check whether this change is needed anymore?

2024-06-12 08:16 UTC, thpralas commented
> Can you check whether this change is needed anymore?

This change is not needed anymore, the test is not failing anymore on devel branch.

2024-06-12 10:08 UTC, TuomasBorman commented
Thanks, closing

2024-06-12 10:08 UTC, closed without merging