Batch transformations. #429
microbiome/mia pull request #618
Opened 2024-07-30 14:32 UTC by ake123

Batch transformations. #429

2024-08-05 12:40 UTC, TuomasBorman requested changes
I think this is too complex, instead you could consider own method for SingleCellExperiment. Something like this

SCE_method <- function(x, altexp = reducedDimanames(tse), ...){
    # Check that specified altexps are found from x
    # Check that assay.type are found from specified altexps
    lapply(altExps(x)[altexp], .check_assay_present)
    # Apply transformation to x
    x <- .perform_transformation(x)
    # If altexp is not NULL, apply transformation to altexps
    altExps(x)[altexp] <- bplapply(altExps(x)[altexp], ...)
}

SE_method <- function(){
    # Input checks
    # Apply transformation
    x <- .perform_transformation(x)
}

2024-08-05 20:29 UTC, antagomir commented
I agree that direct support for SCE is probably the way to go when altExps are supported. 

This in the above example mixes concepts: `altexp = reducedDimanames(tse)`? Should it be `altexp = altExpNames(tse)`?

2024-08-05 20:31 UTC, TuomasBorman commented
> I agree that direct support for SCE is probably the way to go when altExps are supported.
> 
> This in the above example mixes concepts: `altexp = reducedDimanames(tse)`? Should it be `altexp = altExpNames(tse)`?

Yep, I fixed the comment

2024-08-27 20:49 UTC, antagomir commented
Status of this one?

2024-08-28 09:44 UTC, ake123 commented
rewriting and debugging it as suggested

2024-09-01 13:38 UTC, TuomasBorman commented on R/transformCounts.R
> +
This is much more complex than should be

2024-09-01 13:39 UTC, TuomasBorman commented on R/transformCounts.R
>  .apply_transformation_from_vegan <- function(mat, method, MARGIN, reference = ref_vals,
Why the function is duplicated?

2024-09-01 14:12 UTC, TuomasBorman commented
Can you revert the already made modifications? Something like this creates a good start point

```
#' @rdname transformAssay
#' @export
setGeneric("transformAssay", signature = c("x"),
    function(x,  ...)
    standardGeneric("transformAssay"))

#' @rdname transformAssay
#' @export
setMethod("transformAssay", signature = c(x = "SummarizedExperiment"),
    function(x,
        assay.type = "counts", assay_name = NULL,
        method = c("alr", "chi.square", "clr", "css", "css.fast", "frequency", 
                  "hellinger", "log", "log10", "log2", "max", "normalize", 
                  "pa", "range", "rank", "rclr", "relabundance", "rrank",
                  "standardize", "total", "z"),
        MARGIN = "samples",
        name = method,
        pseudocount = FALSE,
        ...){
        #
        x <- .transform_assay(
            x = x, method = method, name = name, assay.type = assay.type,
            MARGIN = MARGIN, pseudocount =  pseudocount, ...)
        return(x)
    }
)

.transform_assay <- function(
        x, assay.type = "counts", assay_name = NULL,
        method = c(
            "alr", "chi.square", "clr", "css", "css.fast", "frequency", 
            "hellinger", "log", "log10", "log2", "max", "normalize", 
            "pa", "range", "rank", "rclr", "relabundance", "rrank",
            "standardize", "total", "z"),
         MARGIN = "samples",
         name = method,
         pseudocount = FALSE,
        ...){
    # Input check
    if (!is.null(assay_name)) {
        .Deprecated(old="assay_name", new="assay.type", "Now assay_name is 
                deprecated. Use assay.type instead.")
        assay.type <- assay_name
    }
    
    # Check assay.type
    .check_assay_present(assay.type, x)
    
    # Check name
    if(!.is_non_empty_string(name) ||
       name == assay.type){
        stop("'name' must be a non-empty single character value and be ",
             "different from `assay.type`.",
             call. = FALSE)
    }
    # Check method
    # If method is not single string, user has not specified transform method,
    # or has given e.g. a vector
    if(!.is_non_empty_string(method)){
        stop("'method' must be a non-empty single character value.",
             call. = FALSE)
    }
    method <- match.arg(method, several.ok = FALSE)
    # Check that MARGIN is 1 or 2
    MARGIN <- .check_MARGIN(MARGIN)
    # Check pseudocount
    if( !.is_a_bool(pseudocount) && !(is.numeric(pseudocount) && 
                                      length(pseudocount) == 1 && pseudocount >= 0) ){
        stop("'pseudocount' must be TRUE, FALSE or a number equal to or 
                 greater than 0.",
             call. = FALSE)
    }
    # Input check end
    #
    # Get the method and abundance table
    method <- match.arg(method)
    assay <- assay(x, assay.type)
    
    # Apply pseudocount, if it is not 0
    assay <- .apply_pseudocount(assay, pseudocount, ...)
    # Store pseudocount value and set attr equal to NULL
    pseudocount <- attr(assay, "pseudocount")
    attr(assay, "pseudocount") <- NULL
    
    # Calls help function that does the transformation
    # Help function is different for mia and vegan transformations
    if( method %in% c("log10", "log2", "css", "css.fast") ){
        transformed_table <- .apply_transformation(
            assay, method, MARGIN, ...)
    } else {
        transformed_table <- .apply_transformation_from_vegan(
            assay, method, MARGIN, ...)
    }
    
    # Add pseudocount info to transformed table
    attr(transformed_table, "parameters")$pseudocount <- pseudocount
    
    # Assign transformed table to assays
    assay(x, name, withDimnames=FALSE) <- transformed_table
    x
}

#' @rdname transformAssay
#' @export
setMethod("transformAssay", signature = c(x = "SingleCellExperiment"),
    function(x, altexp = altExpNames(x), ...){
        # Check altexp
        if( !(is.null(altexp) || (!is.null(altexp) && all(altexp %in% altExpNames(x)))) ){
            stop(".", call. = FALSE)
        }
        browser()
        # Transform the main object
        x <- .transform_assay(x, ...)
        altExps(x) <- lapply(altExps(x), function(y){
            .transform_assay(y, ...)
        })
        return(x)
    }
)
```

2024-09-09 08:30 UTC, TuomasBorman requested changes
Can you still add unit tests, that altexp works as expected?

2024-09-09 08:30 UTC, TuomasBorman commented on R/transformCounts.R
> +#' altExp(tse,"species")
Add space after #

2024-09-09 08:30 UTC, TuomasBorman commented on R/transformCounts.R
> +#' altExp(tse,"species")
I made the changes, see those

2024-09-09 08:30 UTC, TuomasBorman commented on R/transformCounts.R
> +#' altExp(tse,"species") <- transformAssay(tse, method = "relabundance",rank = "species", na.rm = FALSE)
There is no rank parameter in transformAssay()

2024-09-09 08:30 UTC, TuomasBorman commented on R/transformCounts.R
> -
Why this was removed?

2024-09-09 08:31 UTC, TuomasBorman commented on R/transformCounts.R
> +#' altExp(tse,"species") <- transformAssay(tse, method = "relabundance",rank = "species", na.rm = FALSE)
I made the changes

2024-09-21 18:52 UTC, TuomasBorman approved these changes

2024-09-21 19:39 UTC, merged