Fix importTaxpasta
microbiome/mia pull request #619
Opened 2024-07-31 17:11 UTC by d-callan

using taxpasta via nf-core/taxprofiler v1.1.8 and tried to use importTaxpasta to get a tse. I got an error like `type field has unsupported value` (see [here](https://github.com/joey711/biomformat/blob/0de05b1e78ea6ed42e079e07ccb13cecfd9eba6a/R/validity-methods.R#L66)). after some digging around i see it looks like the taxpasta biom leaves this field empty.

this pr represents a proposal to have this type default to 'OTU table'. it also proposes making `addHierarchyTree` optional when importing taxpasta data. my particular use case doesnt require it, and its a bit time consuming. 

i also notice addHierarchyTree seems to not handle fully unclassified entities well. Im considering improving that situation out of scope for this PR unless someone objects, and am happy to file an issue if i dont find one once i have more details. but its also influenced my desire to make it optional in this context, so thought id mention it here.

2024-08-01 10:24 UTC, antagomir commented
These suggestions sound good to me but it would be good to see what @TuomasBorman has to say.

2024-08-05 06:23 UTC, TuomasBorman requested changes
Looks good!

1. Can you add description for the new parameter

\code{Logical scalar}. Specifies whether to calculate and add hierarchy tree. (Default: \code{TRUE})

2. To DESCRIPTION file, add your name

2024-08-05 06:23 UTC, TuomasBorman commented on R/importTaxpasta.R
> +    }
Use

if( .is_a_bool(add.tree) )

2024-08-05 06:23 UTC, TuomasBorman commented on R/importTaxpasta.R
> +importTaxpasta <- function(file, addHierarchyTree = TRUE) {
We are using certain naming convention (I believe we have forgot to add it in guidelines) but:

Class: SummarizedExperiment
Exported function: exportedFunction
Internal function: .internal_function
Parameter: parameter.name

--> So this would be add.hierearchy.tree. However, I would prefer shorter name "add.tree"

2024-08-05 06:23 UTC, TuomasBorman commented on R/importTaxpasta.R
> +    type <- ifelse(type == "", 'OTU table', type)
Can you add comment what it does here? Why are you overwriting the type from the file? It makes the debugging easier if something happens in the future

2024-08-05 06:23 UTC, TuomasBorman commented on R/importTaxpasta.R
> +    type <- ifelse(type == "", 'OTU table', type)
I mean you already explained it in this PR, but it is also good to add in the code

2024-08-05 06:23 UTC, TuomasBorman commented on R/importTaxpasta.R
> +    type <- ifelse(type == "", 'OTU table', type)
Also you are using "" and ''. To harmonize coding style, you could modify 'OTU table' to this "OTU table"

2024-08-05 06:23 UTC, TuomasBorman commented on R/importTaxpasta.R
> +	if (addHierarchyTree) tse <- addHierarchyTree(tse)
The indentation is off. This is inside if statement so the indentation should be +4 spaces

2024-08-05 06:31 UTC, TuomasBorman commented
I think set.ranks should also be optional (not related to the issue, but might be good to fix here also). You are free to do that also if you want, but I can also do that after you have finished finalizing your code.

Your plan about addHiearchyTree: Sounds very good! We can continue this in separate issue/PR to discuss about the solution.

2024-08-08 16:46 UTC, d-callan commented
hi @TuomasBorman and thanks for the detailed feedback! I wasnt sure how people would feel about these changes and so didnt put any real effort into styling/ linting/ etc yet, but i will do that now. I like your suggestions, but wonder about `addHierarchyTree` -> `add.tree`.. funnily enough i usually prefer longer names than shorter for things. i like the explicitness of it, the clarity and readability, as i figure anyone who knows the method for addHierarchyTree will immediately guess what the similarly named parameter does and vice versa. ill make it `add.tree` if you like, but wonder if youd be alright w `add.hierarchy.tree`

2024-08-08 17:03 UTC, d-callan commented on R/importTaxpasta.R
> +	if (addHierarchyTree) tse <- addHierarchyTree(tse)
ive maintained the existing indentation here, just added the conditional before. are single-line if statements against mia convention?

2024-08-08 17:08 UTC, d-callan commented on R/importTaxpasta.R
> +	if (addHierarchyTree) tse <- addHierarchyTree(tse)
^ gen q. i do appreciate convention

2024-08-09 06:09 UTC, TuomasBorman commented on R/importTaxpasta.R
> +	if (addHierarchyTree) tse <- addHierarchyTree(tse)
single-line if statements are ok if they are easy to read (as here). To be honest, I am not 100% sure what my comment is referring; this line is ok; sorry about confusion.

2024-08-09 06:14 UTC, TuomasBorman commented on R/importTaxpasta.R
>          tse <- agglomerateByRanks(tse, agglomerate.tree = TRUE)
agglomerate.tree --> update.tree (Can you change this line)

We updated parameter names this summer, and I believe this imporTaxpasta was merged during the naming process and we did not notice this earlier

2024-08-09 06:25 UTC, TuomasBorman commented
> hi @TuomasBorman and thanks for the detailed feedback! I wasnt sure how people would feel about these changes and so didnt put any real effort into styling/ linting/ etc yet, but i will do that now. I like your suggestions, but wonder about `addHierarchyTree` -> `add.tree`.. funnily enough i usually prefer longer names than shorter for things. i like the explicitness of it, the clarity and readability, as i figure anyone who knows the method for addHierarchyTree will immediately guess what the similarly named parameter does and vice versa. ill make it `add.tree` if you like, but wonder if youd be alright w `add.hierarchy.tree`

I understand your point about the importance of explicitness and transparency in naming. However, using add.tree aligns well with other existing parameters, such as update.tree. Additionally, the risk of misunderstanding is minimal because the documentation is intended to clearly explain the functionality. However, you pointed a problem in the documentation as it is not currently clearly explaining where the tree comes from. (Would you be able to fix this?) The documentation should describe that tree is calculated with addHierarchyTree. I guess the names are balance; they should be clear enough but not too long since they might be annoying for some users.

2024-08-09 14:32 UTC, d-callan commented
ok. i believe all comments addressed now, but let me know.

2024-08-09 15:29 UTC, TuomasBorman approved these changes
Looks very nice. Will be merged when checks pass. Thanks!

2024-08-09 18:39 UTC, merged

2024-08-13 17:50 UTC, TuomasBorman commented
@d-callan I was pushing to Bioconductor and noticed that the maximum size of file can be 5 MB. However, the biom file is over 10 MB. Can you subset it? Unfortunately, I did not remember this earlier.

2024-08-17 02:27 UTC, d-callan commented
hey. sry. this week has been awful at work and this got away from me. fixing now.